language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.2
    - nightly
notifications:
    email: false
after_success:
    - julia -e 'using Pkg; import DICOM; cd(joinpath(dirname(pathof(DICOM)),"../")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'